### https://gist.github.com/bubbobne/fe5f2db65acf039be6a9fd92fc9c7233

#MIT License
#
#Copyright (c) 2017 Daniele Andreis
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

#
#Edits by joseph.rios@nasa.gov:
#
#Converted into a domain versus an API.
#Fixed "Point2d" syntax errors
#Removed responses section.
#Removed non-geojson definitions
#Commented out unsupported elements in UTM (multi*, GeometryCollection)
#Updated externalDocs links to point to RFC
#Improved "description" fields.
#issmith1 trying github push , switch to yaml 
#retrying github push.

definitions:
        
  Geometry:
    type: object
    description: GeoJSon geometry
    discriminator: type
    required:
      - type
    externalDocs:
      url: https://tools.ietf.org/html/rfc7946#section-3.1
    properties:
      type:
        type: string
        enum:
        - Point
        - LineString
        - Polygon
#        - MultiPoint
#        - MultiLineString
#        - MultiPolygon
        description: the geometry type
  
  Point2D:
    type: array
    maxItems: 2
    minItems: 2
    items:
      type: number
  
  
  Point:
    type: object
    description: GeoJSon Point, limited to 2D.
    externalDocs:
      url: https://tools.ietf.org/html/rfc7946#section-3.1.2
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            $ref: '#/definitions/Point2D'
    
  LineString:
    type: object
    description: GeoJSon LineString. Points all 2D.
    externalDocs:
      url: https://tools.ietf.org/html/rfc7946#section-3.1.4
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: array
            items:
              $ref: '#/definitions/Point2D'

  Polygon:
    type: object
    description: GeoJSon Polygon. Points all 2D.
    externalDocs:
      url: https://tools.ietf.org/html/rfc7946#section-3.1.6
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: array
            items:
              type: array
              items:
                $ref: '#/definitions/Point2D'
      
#  MultiPoint:
#    type: object
#    description: GeoJSon geometry
#    externalDocs:
#      url: https://tools.ietf.org/html/rfc7946#section-3.1.3
#    allOf:
#      - $ref: "#/definitions/Geometry"
#      - properties:
#          coordinates:
#            type: array
#            items:
#              $ref: '#/definitions/Point2D'
            
#  MultiLineString:
#    type: object
#    description: GeoJSon geometry
#    externalDocs:
#      url: https://tools.ietf.org/html/rfc7946#section-3.1.5
#    allOf:
#      - $ref: "#/definitions/Geometry"   
#      - properties:
#          coordinates:
#            type: array
#            items:
#              type: array
#              items:
#                $ref: '#/definitions/Point2D'
#      
      
#  MultiPolygon:
#    type: object
#    description: GeoJSon geometry
###    externalDocs:
#      url: https://tools.ietf.org/html/rfc7946#section-3.1.7
#    allOf:
#      - $ref: "#/definitions/Geometry"
#      - properties:
#          coordinates:
#            type: array
#            items:
#              type: array
#              items:
#                type: array
#                items:
#                  $ref: '#/definitions/Point2D'
      
##  GeometryCollection:
#    type: object
#    description: GeoJSon geometry collection
#    required:
#     - type
#     - geometries
#    externalDocs:
#      url: https://tools.ietf.org/html/rfc7946#section-3.1.8
#    properties:
#      type:
#        type: string
#        enum:
#        - GeometryCollection
#     geometries:
#          type: array
#          items:
#            $ref: '#/definitions/Geometry'