---
swagger: "2.0"
info:
  description: "This API describes the minimum interface that a USS must implement\
    \ to  be part of the USS Network.  This API allows for communication of data \
    \ between USS Instances and from FIMS to a USS regarding new USS Instances."
  version: "v1"
  title: "USS Required API"
  termsOfService: "\nA. No Warranty: THE SUBJECT SOFTWARE IS PROVIDED \"AS IS\" WITHOUT\
    \ ANY WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY, INCLUDING,\
    \ BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL CONFORM TO SPECIFICATIONS,\
    \ ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,\
    \ OR FREEDOM FROM INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE\
    \ ERROR FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM TO\
    \ THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER, CONSTITUTE AN\
    \ ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT OF ANY RESULTS, RESULTING\
    \ DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY OTHER APPLICATIONS RESULTING FROM\
    \ USE OF THE SUBJECT SOFTWARE. FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES\
    \ AND LIABILITIES REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE,\
    \ AND DISTRIBUTES IT \"AS IS.\"\n\nB. Waiver and Indemnity: RECIPIENT AGREES TO\
    \ WAIVE ANY AND ALL CLAIMS AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS\
    \ AND SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT''S USE OF THE\
    \ SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES, EXPENSES OR LOSSES\
    \ ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM PRODUCTS BASED ON, OR RESULTING\
    \ FROM, RECIPIENT''S USE OF THE SUBJECT SOFTWARE, RECIPIENT SHALL INDEMNIFY AND\
    \ HOLD HARMLESS THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS,\
    \ AS WELL AS ANY PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW. RECIPIENT''S\
    \ SOLE REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL TERMINATION\
    \ OF THIS AGREEMENT.\n"
  contact:
    name: "NASA Ames Research Center, Aviation Systems Division"
    url: "https://utm.arc.nasa.gov/"
    email: "joseph.rios@nasa.gov"
  license:
    name: "NASA Open Source Agreement"
    url: "https://ti.arc.nasa.gov/opensource/nosa/"
host: "uss.defined.url"
basePath: "/uss"
tags:
- name: "A. Required Endpoints"
- name: "B. Connections"
  description: "USS publishes position reports on this Websocket  connection. The URI scheme should be 'wss'.\n"
schemes:
- "https"
- "wss"

security:
- ussapi_security:
  - "utm.nasa.gov_read.min_data"
paths:
  /constraints:
    post:
      tags:
      - "A. Required Endpoints"
      summary: "Allow constraints to be submitted from authorized entities."
      operationId: "postConstraint"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "message"
        description: "The message being sent"
        required: true
        schema:
          $ref: 'https://api.swaggerhub.com/domains/utm/commons/v1#/definitions/ConstraintMessage'
      responses:
        201:
          description: "Constraint data received. "
          schema:
            $ref: 'https://api.swaggerhub.com/domains/utm/commons/v1#/definitions/UTMRestResponse'
      security:
      - ussapi_security:
        - "utm.nasa.gov_write.constraint"
        - "utm.nasa.gov_all.all"
  /utm_messages:
    post:
      tags:
      - "A. Required Endpoints"
      summary: "Allow other authorized entities to send a message to this USS."
      description: "Allows another USS or FIMS to POST a message to this USS."
      operationId: "postUtmMessage"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "message"
        description: "The message being sent"
        required: true
        schema:
          $ref: 'https://api.swaggerhub.com/domains/utm/commons/v1#/definitions/UTMMessage'
      responses:
        201:
          description: "Message data received."
          schema:
            $ref: 'https://api.swaggerhub.com/domains/utm/commons/v1#/definitions/UTMRestResponse'
      security:
      - ussapi_security:
        - "utm.nasa.gov_write.message"
  /uss:
    post:
      tags:
      - "A. Required Endpoints"
      summary: "Share USS Instance data"
      description: "As per the USS Discovery Service specification, this endpoint\
        \ is for receiving messages about the USS Network from the USS Discovery Service.\
        \  For example, when a new USS Instance is registered, that announcement would\
        \ come to this endpoint."
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "message"
        description: "The USS Instance information being sent"
        required: true
        schema:
          $ref: 'https://api.swaggerhub.com/domains/utm/commons/v1#/definitions/UssInstance'
      responses:
        201:
          description: "USS Instance data received."
          schema:
            $ref: 'https://api.swaggerhub.com/domains/utm/commons/v1#/definitions/UTMRestResponse'
      security:
      - ussapi_security:
        - "utm.nasa.gov_write.operation"
  /negotiations:
    post:
      tags:
      - "A. Required Endpoints"
      summary: "Allow other USSs to submit a negotiation request"
      description: "A POST to the negotiations endpoint is interpretted as a request\
        \ for alteration in an existing operation managed by the receiving USS.  The\
        \ requesting USS supplies a GUFI that references the operation that may be\
        \ altered if the request is granted by the receiving USS."
      operationId: "postNegotiation"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "operation"
        description: "The NegotiationMessage data"
        required: true
        schema:
          $ref: 'https://api.swaggerhub.com/domains/utm/commons/v1#/definitions/NegotiationMessage'
      responses:
        200:
          description: "OK"
          schema:
            $ref: 'https://api.swaggerhub.com/domains/utm/commons/v1#/definitions/UTMRestResponse'
        400:
          description: "Problem with submitted data"
      security:
      - ussapi_security:
        - "utm.nasa.gov_write.message"
  /operations:
    get:
      tags:
      - "A. Required Endpoints"
      summary: "Request information regarding Operations"
      description: "Allows querying for Operation data."
      operationId: "getOps"
      produces:
      - "application/json"
      parameters:
      - name: "fields"
        in: "query"
        description: "The specific subset of fields to return. Comma separated list.\
          \ Default will be all fields when this parameter is not provided in the\
          \ query. Duplicate field names not allowed and server may reject query if\
          \ duplicates are provided. If field names are provided that are not part\
          \ of the request model, the server may either reject the query or ignore\
          \ the improper fields. Maximum 20 field values supported. If more than 20\
          \ fields are required, then this parameter should not be used so that all\
          \ fields are returned."
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "csv"
        maxItems: 20
        minItems: 1
        uniqueItems: true
      - name: "sort"
        in: "query"
        description: "A valid field name to use for sorting records. If multiple fields\
          \ are provided, the sorting is based on the ordered priorty of that list."
        required: false
        type: "string"
        default: "time_submitted"
      - name: "sort_increasing"
        in: "query"
        description: "For optional use with the 'sort' parameter. If 'sort' is not\
          \ provided, then 'sort_increasing' will be ignored. Boolean value.  If multiple\
          \ fields are provided in the 'sort' paramenter, this boolean value will\
          \ apply to all of them."
        required: false
        type: "boolean"
        default: true
      - name: "limit"
        in: "query"
        description: "The maximum number or records to return."
        required: false
        type: "integer"
        default: 10
        maximum: 100
        minimum: 1
        format: "int32"
      - name: "offset"
        in: "query"
        description: "The index from which to begin the list of returned records."
        required: false
        type: "integer"
        default: 0
        format: "int32"
      responses:
        200:
          description: "Successful data request. Response includes requested data."
          schema:
            type: "array"
            items:
              $ref: 'https://api.swaggerhub.com/domains/utm/commons/v1#/definitions/Operation'
        400:
          description: "Bad request. Typically validation error. Fix your request\
            \ and retry."
        429:
          description: "Too many recent requests from you. Wait to make further queries."
      security:
      - ussapi_security:
        - "utm.nasa.gov_read.operation"
    post:
      tags:
      - "A. Required Endpoints"
      summary: "Allow other USSs to submit their UAS Operations."
      description: "A POST to the operations endpoint allows for sharing of operational\
        \ data between USSs.  This is the primary mechanism by which USSs become aware\
        \ of each others' UAS operations.<br/><br/>\nA USS is required to share operation\
        \ data with other USSs that may have interacting UAS Operations.  This potential\
        \ interaction is known through the data provided via the USS Service Discovery\
        \ mechanism (see https://app.swaggerhub.com/apis/utm/ussdiscovery/v2)."
      operationId: "postOp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "operation"
        description: "The operation data"
        required: true
        schema:
          $ref: 'https://api.swaggerhub.com/domains/utm/commons/v1#/definitions/Operation'
      responses:
        201:
          description: "Operation data received."
          schema:
            $ref: 'https://api.swaggerhub.com/domains/utm/commons/v1#/definitions/UTMRestResponse'
        400:
          description: "Bad request. Typically validation error. Fix your request\
            \ and retry."
        429:
          description: "Too many recent requests from you. Wait to make further submissions."
      security:
      - ussapi_security:
        - "utm.nasa.gov_write.operation"
        - "utm.nasa.gov_write.publicsafety"
    put:
      tags:
      - "A. Required Endpoints"
      summary: "Submit updates to a previously communicated UAS Operation."
      description: "Allows for other USSs to update a previous plan submission."
      operationId: "putOp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "operation"
        description: "Operational plan with the following properties:\n  1. Contains\
          \ a valid uss_operation_id.\n  2. time_available_end value that is in the\
          \ future.\n  3. No date-time fields that are in the past are modified.\n\
          \  4. Other rules for a USS Operation POST are satisfied.\n"
        required: true
        schema:
          $ref: 'https://api.swaggerhub.com/domains/utm/commons/v1#/definitions/Operation'
      responses:
        201:
          description: "OK"
          schema: 
            $ref: 'https://api.swaggerhub.com/domains/utm/commons/v1#/definitions/UTMRestResponse'
        400:
          description: "Bad request. Typically validation error. Fix your request\
            \ and retry."
        429:
          description: "Too many recent requests from you. Wait to make further queries."
      security:
      - ussapi_security:
        - "utm.nasa.gov_write.operation"
        - "utm.nasa.gov_write.publicsafety"
  /positions/{gufi}:
    get:
      tags:
      - "B. Connections"
      summary: "Websocket connection for position data"
      description: "Non RESTful endpoint that allows for Position events reported\
        \ by another USS Instance.  When connecting to this Websocket endpoint, the\
        \ consumer must emit an \\'authentication\\' event containing the OAuth2 token\
        \ as described in parameters. Once authenticated, the consumer will receive\
        \ \\'Position\\' events as they are received by USS instances.\n"
      produces:
      - "application/json"
      parameters:
      - name: "gufi"
        in: "path"
        description: "filter by operation ID"
        required: true
        type: "string"
        maxLength: 36
        minLength: 36
        format: "uuid"
      responses:
        200:
          description: "A Position report event"
          schema:
            type: "array"
            items:
              $ref: 'https://api.swaggerhub.com/domains/utm/commons/v1#/definitions/Position'

securityDefinitions:
  ussapi_security:
    type: "oauth2"
    tokenUrl: "https://thisserver.com/oauth/token"
    flow: "application"
    scopes:
      utm.nasa.gov_read.constraint: "Subject can read UTM constraint data"
      utm.nasa.gov_write.constraint: "Subject can read, create, and update UTM constraint\
        \ data. This means that the Subject can define areas that restrict other operations."
      utm.nasa.gov_read.min_data: "Subject can read data which has been minimized\
        \ for example, by redacting some properties"
      utm.nasa.gov_write.operation: "Subject can read, create, and update operational\
        \ data such as USS Instance data"
      utm.nasa.gov_read.operation: "Subject can read operational data such as USS\
        \ Instance data"
      utm.nasa.gov_write.message: "Subject can read, create, and update message data\
        \ such as UTM Message and Negotiations"
      utm.nasa.gov_read.message: "Subject can read message data such as UTM Message\
        \ and Negotiations"
      utm.nasa.gov_write.publicsafety: "Subject can read, create, and update operations\
        \ that are designated public safety operations."
      utm.nasa.gov_all.all: "Subject can read, create, and udpate data throughout\
        \ UTM. Used sparingly, if ever. Goes against priciple of least privelege,\
        \ but may be necessary in some cases."